### ISSUE TITLE
PR environment fails to destroy with missing state

### ISSUE THREAD

**Issue by jjgriff93** [UCLH-Foundry/FlowEHR#186]
https://github.com/UCLH-Foundry/FlowEHR/actions/runs/4470589453/jobs/7855095132#step:6:1068

**Comment by t-young31** [comment]
this is [reproducable](https://github.com/UCLH-Foundry/FlowEHR/pull/195#issuecomment-1481159704) and annoying because it leaves the rg orphaned

<img width="196" alt="Screenshot 2023-03-23 at 13 13 28" src="https://user-images.githubusercontent.com/39765193/227215128-e62e13ce-6bfd-47b4-ba3d-3f18bdb3c22c.png">
