### ISSUE TITLE
Private, Persistent Build Agent

### ISSUE THREAD

**Issue by damoodamoo** [UCLH-Foundry/FlowEHR#199]
Discussed as a group and plan is confirmed:

- [x] Move bootstrap (TF state storage and acr) creation from `/bootstrap/shared/management` to a separate repo (`azure-bootstrap`?). Make it a public template
- [x] Create private fork so we can check in state with the correct IP range (see https://github.com/UCLH-Foundry/Book-of-FlowEHR/pull/184)
- [x] Change local deployments of FlowEHR to use local state
- [x] Rename `bootstrap` to `auth` and use just for the CI auth app creation (which is in `bootstrap/ci` currently)
- [x] Move naming suffix logic from `bootstrap/shared/naming` to `infrastructure/core`
- [x] Move IP exception data call from `bootstrap/local` to `infrastructure/core`
- [x] Move `infrastructure/core/build-agent` logic out of repo to the separate bootstrap repo
  - [x] Look at most cost-efficient option - either convert to burst able VM or turn on ACI when needed
  - [x] Remove agent is running check
- [x] Add GitHub env vars and populate in terragrunt using get_env:
  - [x] `ci_resource_group`
  - [x] `ci_storage_account`
  - [x] `ci_container_registry`
  - [x] `ci_peering_vnet` - vnet to peer to (any other data required can be looked up via TF data)
- [x] Update logic in `./terragrunt.hcl` to populate `remote_state` with these values if not running locally (i.e. if `tf_in_automation` is true), otherwise set to local state
- [x] Remove non-core logic from GH action
- [x] Make `runs-on` in the actions.yaml dynamic if possible and have a GH var that passes the build agent name
- [x] Add deployment branch environment protection for infra-test and app-dev to only use from main
- [x] Update getting started docs
- [x] Create a bootstrap for dev (`infra-test` & `app-dev`) - we will create another one when we have a prod environment to ensure separation when hosting live data
- [ ] Add the relevant vars to the respective GH environments and deploy `infra-test` and `app-dev`

**Comment by jjgriff93** [comment]
After some soul searching and convincing from Tom, happy to concede and move the bootstrapping out of FlowEHR into a separate repo. So as I see it this would involve:

- [ ] Move bootstrap (TF state storage and acr) creation from `/bootstrap/shared/management` to a separate repo (`azure-bootstrap`?)
- [ ] Change local deployments of FlowEHR to use local state
- [ ] Rename `bootstrap` to `auth` and use just for the CI auth app creation (which is in `bootstrap/ci` currently)
- [ ] Move naming suffix logic from `bootstrap/shared/naming` to `infrastructure/core`
- [ ] Move IP exception data call from `bootstrap/local` to `infrastructure/core`
- [ ] Move `infrastructure/core/build-agent` logic out of repo to the separate bootstrap repo
- [ ] Update `config.yaml` to have an optional `ci` block with:
  - [ ] `resource_group_name`
  - [ ] `storage_account_name`
  - [ ] `container_registry_name`
  - [ ] `peering` - any network peering config needed for core to peer to bootstrap vnet
- [ ] Update logic in `./terragrunt.hcl` to populate `remote_state` with these values if not running locally (i.e. if `tf_in_automation` is true), otherwise set to local state

Let's discuss in our meeting!

**Comment by t-young31** [comment]
VM setup script: https://github.com/UCLH-Foundry/Book-of-FlowEHR/blob/main/devops.md

**Comment by jjgriff93** [comment]
Documenting here for reference. There were some issues when deploying our actions workflows from the build agent VM with file permissions

- Initially we ran the GH runner service as root. When we did this, files created by the devcontainer (i.e. Terragrunt-generated files) then gave us permission denied in steps where the container needed to read them. I tried all of the various methods in the devcontainer definition to try running the devcontainer as root as well, but to no avail.
- After some reading it looked like it would be better to run the service as a user to avoid these problems. After some effort I got this to work (it wasn't straightforward!) but then we hit a problem where the GitHub action `devcontainer/ci` step wanted to `npm install` globally, which required `usr/bin` access which is reserved for root, and messing with these permissions only gave more errors with sudo etc.
- Solved this by not installing node in the `cloud-init` packages (which install as root), and instead install in our own script so that the directories are all user-owned.

For future runner package requirements that will be used by workflow steps, we should ensure these are installed within our own user-invoked script (where we install node) to avoid any permissions issues

**Comment by jjgriff93** [comment]
## KeyVault connection issues

```Error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
  │ 
  │   with azurerm_key_vault.core,
  │   on main.tf line 35, in resource "azurerm_key_vault" "core":
  │   35: resource "azurerm_key_vault" "core" {
```
There seems to be an inherent issue with the provider where KeyVault reads needed to complete the kv deployment require the private endpoint to be in place when public network is disabled, which in turn requires the key vault id from the deployed key vault. There is a ticket tracking a solution for this https://github.com/hashicorp/terraform-provider-azurerm/issues/9738 however we need to find a workaround for the time being
