### ISSUE TITLE
Configure GitHub Terraform provider with access to UCLH Foundry

### ISSUE THREAD

**Issue by jjgriff93** [UCLH-Foundry/FlowEHR#71]
We should authenticate the [GitHub Terraform provider](https://registry.terraform.io/providers/integrations/github/latest/docs) to the `UCLH-Foundry` org using a [GitHub App](https://docs.github.com/en/apps/creating-github-apps/creating-github-apps/about-apps) for FlowEHR, that enables the provisioning of repositories, teams, branch protections, environments with secrets and user role assignments.

This will be done in the `/serve/hosting` directory where the per-app Terraform deployment will be defined

- [ ] Provision a GitHub app for FlowEHR
- [ ] Initialise the provider in `/serve/hosting`

Design doc: https://github.com/UCLH-Foundry/Book-of-FlowEHR/blob/the-walking-skeleton/milestones/walking-skeleton/building-clinical-product/serve-devops-design.md

**Comment by jedheaj314** [comment]
Requirement is  to code deployment such a that on deployment terraform can automatically create repositories for UCLH apps and should be able to configure secrets/setting for that repository.


Tested GitHub App, to get to the following findings: 

GitHub App:
Could not find a way to provide access to **only** create new repositories and change/create secrets for those newly created repositories with GitHub App (which is installed for an organisation for an user account). It can have access to either all the repositories that belong in the organisation for that account or the specific repository that you specify during GitHub App setup.

Discussed following approaches to solve the problem with @damoodamoo and Tom (UCLH).


**1. Approach 1: (New organisation)**
Create Organisation for UCLH applications only.

- And setup an organisation token with access to only create new repositories and setup secrets for the repositories inside that organisation.

Or

- And use GitHub App.  Setup GitHub app's private key so that there only be newly created repositories and code will have access to configure/create secrets and other settings for the newly created repositories.




**2. Approach 2: (Dedicated GitHub user)**

In this approach, we create a new dedicated user which is only used for deployment (this part). Token for this user is then used by terraform to create new repositories and setup secrets for those repositories.


**3. Approach 3: (Admin permission)**

In this approach, admin user who is running the deployment can use their own token/credentials. Token for this user is then used by terraform to create new repositories and setup secrets for those repositories.

Discussion will be taking place in stand-up of 23rd Feb 2023 to decide which approach to be used.
